###
POST http://localhost:8080/member/create
Content-Type: application/json

{
  "name" : "sejong",
  "email" :"Test@name.com1",
  "password" : "12345"
}



###
POST http://localhost:8080/doLogin
Content-Type: application/json

{
  "email" :"Test@name.com1",
  "password" : "12345"
}
